# dependabot.yml file with npm

version: 2
updates:
    # Enable version updates for yarn
    - package-ecosystem: 'yarn'
      # Look for `package.json` and `lock` files in the `api` directory
      directory: './api'
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: 'weekly'
          
    # Enable version updates for yarn
    - package-ecosystem: 'yarn'
      # Look for `package.json` and `lock` files in the `client` directory
      directory: './client'
      # Check the npm registry for updates every day (weekdays)
      schedule:
          interval: 'weekly'

    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          # Check for updates to GitHub Actions every weekday
          interval: 'daily'
