name: CD-API

on: workflow_dispatch

defaults:
    run:
        shell: bash

env:
    AZURE_WEBAPP_NAME: cloud-vod-api # set this to your application's name
    AZURE_WEBAPP_PACKAGE_PATH: 'api' # set this to the path to your web app project, defaults to the repository root

jobs:
    deploy:
        name: 'Deploy API'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Use Node
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.x
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build API
              run: yarn build
              working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
            - name: 'Deploy to Azure WebApp'
              uses: azure/webapps-deploy@v2.1.6
              with:
                  app-name: ${{ env.AZURE_WEBAPP_NAME }}
                  publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                  package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
