# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CD-Client

on:
    push:
        branches: [master, ui-cd]

defaults:
    run:
        working-directory: client

jobs:
    deploy:
        timeout-minutes: 3
        name: deploy-client
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Cache NPM dependencies
              id: cache
              uses: actions/cache@v2.1.5
              with:
                  path: |
                      client/node_modules
                  key: ${{ runner.OS }}-npm-cache-client-${{ hashFiles('.github/workflows/CI - Client.yml') }}-${{ hashFiles('client/package-lock.json') }}-${{ matrix.node-version }}
            - name: Setup Node
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: 14.x
            - name: Install Uncached Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
            - name: Run Tests
              run: npm test
            - name: Build Client
              run: npm run build --if-present
            - name: Publish built code to a branch
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTION_DEPLOY_KEY }}
                  publish_dir: client
                  publish_branch: client-CD
