# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI-Client

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

defaults:
    run:
        working-directory: client

jobs:
    build:
        timeout-minutes: 3
        name: build-client
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 15.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Fail if run by dependabot
              if: github.actor == 'dependabot[bot]'
              run: exit 1
            - uses: actions/checkout@v2
            - name: Cache NPM dependencies
              id: cache
              uses: actions/cache@v2.1.5
              with:
                  path: |
                    client/node_modules
                  key: ${{ runner.OS }}-npm-cache-client-${{ hashFiles('.github/workflows/CI - Client.yml') }}-${{ hashFiles('client/yarn.lock') }}-${{ matrix.node-version }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: ${{ matrix.node-version }}
            - name: yarn install
              run: yarn install
            - name: yarn build
              run: yarn build
            - run: yarn test
