# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x, 15.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
              env:
                  # Pull environmental variable from Github
                  AadClientId: ${{ secrets.AADCLIENTID }}
                  AadSecret: ${{ secrets.AADSECRET }}
                  AadTenantDomain: ${{ secrets.AADTENANTDOMAIN }}
                  AadTenantId: ${{ secrets.AADTENANTID }}
                  AccountName: ${{ secrets.ACCOUNTNAME }}
                  Location: ${{ secrets.LOCATION }}
                  ResourceGroup: ${{ secrets.RESOURCEGROUP }}
                  SubscriptionId: ${{ secrets.SUBSCRIPTIONID }}
                  StorageConnection: ${{ secrets.STORAGECONNECTION }}
                  TransformName: ${{ secrets.TRANSFORMNAME }}
                  BASE_URL: ${{ secrets.BASE_URL }}
                  AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
                  AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
                  AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
